---
title: "Disclaimer"
output: distill::distill_article
---

## General Disclaimer
The blog posts, statistical analyses, the data visualizations and conclusions, as well as the underlying source code (together: the "blog article/articles") on this website come "as is" and are without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. in no event shall the  author or copyright holder be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the blog articles or the use or other dealings in the blog articles.

## External Links
Despite thorough review, the author is not taking any responsibility or liability for external sources that are being linked to. The liability completely lies with the operators of these external sources.

## Medical Disclaimer
The contents of the blog articles are of educational nature and are intended as general information and learning material. The views expressed are explicitly of personal nature and the author does not represent nor speak for his employer or professional group. The author is by no means giving any medical advice, nor making diagnoses and is explicitly not giving specific recommendations regarding diseases, conditions ot the treatment thereof. The contents of the blog articles are not suited to be applied to real patient cases and if treatments, applications or dosages are mentioned, no guarantee can be given for the correctness and completeness of the information. The content and information on this blog cannot replace the clinical judgment of a healthcare professional.

## Jurisdiction
The blog is hosted in the Federal Republic of Germany. The place of Jurisdiction for any claims arising regarding the blog or the blog articles is the Federal Republic of Germany.
